SOURCES = Adapter.cpp Cell.cpp Controller.cpp Counter.cpp EnemyFighter.cpp FightersManager.cpp IFighter.cpp IProjectile.cpp IWOFModel.cpp Map.cpp PlayerFighter.cpp ProjectileManager.cpp TerminalView.cpp ViewModel.cpp Wave.cpp main.cpp
all:
g++ -std=c++0x -g -o warOfFighter $(SOURCES) -lncurses
